# Translation Channels
Data related to video streams translation table

| Parameter | Description | Type | Required | Public |
|:----------|-------------|------|----------|--------|
| `name` | Name of video stream channel | string | **yes** | **yes** |
| `url` | URL of translation channel | Url | **yes** | **yes** |
| `video_stream_id` | Id of video stream  | string | - | - |
| `channel_id` | Id of main channel inside the video stream | string | - | - |


### List all Video Stream Channel [v1/translation_channels] [GET]
Get a list of all available translation channels in video stream

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>


+ Response 200 (application/vnd.api+json)

{
    "data": [
        {
            "type": "translation_channel",
            "relationships": {
                "channel": {
                    "links": {
                        "self": "/v1/translation_channel/2/relationships/channels",
                        "related": "/v1/video-channels/2"
                    }
                },
                "video-stream": {
                    "links": {
                        "self": "/v1/translation_channel/2/relationships/video-stream",
                        "related": "/v1/video-streams/26"
                    }
                }
            },
            "id": 2,
            "attributes": {
                "url": "yt2.test",
                "name": "yt2"
            },
            "links": {
                "self": "/v1/translation_channels/2"
            }
        }
    ],
    "links": {
        "self": "/v1/translation_channels"
    },
    "meta": {
        "count": 1
    },
    "jsonapi": {
        "version": "1.0"
    }
}



### Save list of translation channels [v1/video-streams/id/translation_channels] [POST]
Save list of translation channels to db
+ Parameters
    + id: id of the video stream

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

    + Body

{
    "data": {
        "type": "translation_channel",
        "attributes": {
          "name": "Translation Channel 1",
          "url": "https://example.com/stream1",
          "id":1
        },
        "relationships": {
          "video_stream": {
            "data": {
              "type": "video_stream",
              "id": "26"
            }
          },
          "channels": {
            "data": {
              "type": "video_channel",
              "id": "2"
            }
          }
        }
    }
}


+ Response 201 (application/vnd.api+json)


### Update a specific translation channel [/v1/translation_channels/id] [PATCH]
+ Parameters
    + id: id of the translation channel
Update translation channel in a stream to db

+ Request

    + Headers

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

    + Body

{
    "data": {
        "type": "translation_channel",
        "id": "2",
        "attributes": {
            "name": "Translation Channel Test Updated ",
            "url": "https://example.com/stream1"
        },
        "relationships": {
            "video_stream": {
                "data": {
                    "type": "video_stream",
                    "id": "26"
                }
            },
            "channels": {
                "data": {
                    "type": "video_channel",
                    "id": "2"
                }
            }
        }
    }
}

+ Response 200 (application/vnd.api+json)

{
    "data": {
        "type": "translation_channel",
        "id": "2",
        "attributes": {
            "name": "Translation Channel Test Updated ",
            "url": "https://example.com/stream1"
        },
        "relationships": {
            "video_stream": {
                "data": {
                    "type": "video_stream",
                    "id": "26"
                }
            },
            "channels": {
                "data": {
                    "type": "video_channel",
                    "id": "2"
                }
            }
        }
    }
}
